# Module 2 Assignment: Retail sales - Expanding your analysis

## Background

You're continuing your work for the elderly couple who owns a retail store. In the first part of the analysis, you demonstrated the benefits of digitizing sales data, which impressed your bosses. Now, you'll expand on that progress by incorporating more data points and transitioning from lists to DataFrames, allowing for a more detailed and comprehensive analysis. 

## In order for your submission to be graded correctly, you **MUST**:
* **Use the provided variable names**, otherwise the autograder will not be able to locate the variable for grading. 

* **Replace any instances of `None` with your own code.** 

* **Only modify the cells that start with the comment `# GRADED CELL`**.  

* **Use the provided cells for your solution.** You can add new cells to experiment, but these will be omitted when grading. 

To submit your solution, save it, then click on the `Submit Assignment` button at the top of the page.

<div style="background-color: #FAD888; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
<strong>Important note</strong>: Code blocks with None will not run properly. If you run them before completing the exercise, you will likely get an error. 

</div>

## Table of contents
- [Step 1: Importing Modules](#step-1)
    - [Exercise 1: Import Pandas](#ex1)
- [Step 2: Load the Data](#step-2)
     - [Importing data from a csv file](#importing-data-from-a-csv-file)
        - [Exercise 2: Import data](#ex2)
- [Step 3: Processing and Analyzing the Dataset](#step-3)
    - [Understanding the data](#understanding-the-data)
        - [Exercise 3: Get the data types](#ex3)
    - [Sorting the DataFrame](#sorting-the-dataframe)
        - [Exercise 4: Purchases With the Biggest Sales](#ex4)
    - [Product counts](#product-counts)
        - [Exercise 5: Product name per row](#ex5)
        - [Exercise 6: Units sold per product](#ex6)
    - [Filtering the DataFrame](#filtering-the-dataframe)
        - [Exercise 7: Filter by product name and units sold](#ex7)
    - [Total amount per invoice](#total-amount-per-invoice)
        - [(Optional) Exercise 8: Find the total amount per invoice](#ex8)
    - [Descriptive Statistics](#descriptive-statistics)
        - [Exercise 9: Slicing the DataFrame](#ex9)
        - [Exercise 10: Analyzing the amount per invoice](#ex10) 


<a id="step-1"></a>

## Step 1: Import Modules

It is good practice to import all your required modules at the beginning of your code. For this lab, you will only need `pandas`.

<a id="ex1"></a>

#### Exercise 1: Import Pandas
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%">

**▶▶▶ Directions**

1. Import the <code>pandas</code> module with the alias <code>pd</code> 

</div>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   

- To import packages or libraries, you can use the `import` statement
- The alias, or nickname, can be set using `as`
</details>

In [1]:
# GRADED cell: Exercise 1

### START CODE HERE ###

# Import the pandas module with the common alias
import pandas as pd

### END CODE HERE ###

<a id="step-2"></a>

## Step 2: Loading the Data

You were able to make some great insights from digitizing a few data points, and you want to add more. You ask the owners for their purchase history, as they must have kept a record. You've saved all the data in a CSV file and are now ready to inspect it in Python.

<a id="ex2"></a>

#### Exercise 2: Import Data

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Load the "sales.csv" file into a DataFrame. Save it in a variable called <code>sales_df</code>. <strong> For grading purposes, please don't modify this variable's name</strong>.</li>
        </ol>
</div>


<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   

- Remember that to load a csv file you can use `pd.read_csv()` function. You shouldn't need to pass any arguments other than the file you want to load, but if you want a little more information, you can check out [🔗this tutorial](https://www.geeksforgeeks.org/python-read-csv-using-pandas-read_csv/) .

</details>

In [2]:
# GRADED CELL: Exercise 2

### START CODE HERE ###

# Load the dataset 
sales_df = pd.read_csv("sales.csv")

### END CODE HERE ###

In [3]:
# Inspect the loaded data using head() method
sales_df.head()

invoice_id        date day_of_week                         product_name  \
0      534377  2010-11-22      Monday    RED RETROSPOT TRADITIONAL TEAPOT    
1      534377  2010-11-22      Monday  SET/5 RED RETROSPOT LID GLASS BOWLS   
2      534377  2010-11-22      Monday            BROWN CHECK CAT DOORSTOP    
3      534377  2010-11-22      Monday          TEA BAG PLATE RED RETROSPOT   
4      534377  2010-11-22      Monday                        CHILLI LIGHTS   

   units_sold  price_per_unit  amount  
0           1            7.95    7.95  
1           1            2.95    2.95  
2           1            4.25    4.25  
3           2            0.85    1.70  
4           1            4.95    4.95

<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>

<img src="img/output_ex2.png">


</details>

<a id="step-3"></a>

## Step 3: Processing and Analyzing the Dataset

<a id="Understanding the data"></a>

### Understanding the data
Before you move any further, you want to first understand the data. You've consulted with the owners and verified these descriptions established in your previous analysis:

* `invoice_id`: id of the purchase. The invoice_id will be repeated as many times as different products were in the purchase. In other words, there will be one observation (row) for each product sold in each purchase. 
* `date`: date of the purchase
* `day_of_week`: Monday - Saturday
* `product_name`: description of the product
* `units_sold`: number of units sold of the product
* `price_per_unit`: price for each individual unit of the product
* `amount`: calculated by multiplying `units_sold` with `price_per_unit`

Now you want to know how `pandas` stored each feature, and you can retrieve that with one attribute.

<a id="ex3"></a>
#### Exercise 3: Get the data types
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Get the data types of each feature in the <code>sales_df</code> DataFrame. Store it in the <code>dtypes</code> variable.   
        </ol>
</div>



<br>
<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   

- For grading purposes, do not use the `info()` method here.
- You used this attribute in the first practice lab in this module.
  
</details>

In [4]:
# GRADED CELL: Exercise 3

### START CODE HERE ###

# Get the data types of each feature
feature_types = sales_df.dtypes

### END CODE HERE ###

In [5]:
# Print the result
print(feature_types)

invoice_id          int64
date               object
day_of_week        object
product_name       object
units_sold          int64
price_per_unit    float64
amount            float64
dtype: object


<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>

```text
invoice_id          int64
date               object
day_of_week        object
product_name       object
units_sold          int64
price_per_unit    float64
amount            float64
dtype: object
```


</details>

<a id="sorting-the-dataframe"></a>
### Sorting the DataFrame
Which were the top 10 largest sales amounts recorded in the dataset? One way to figure this out is by sorting the DataFrame by "amount" in descending order. This way your first observations will be the most profitable ones. 

<a id="ex4"></a>

#### Exercise 4: Purchases with Biggest Sales
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Sort <code>sales_df</code> by "amount" in decreasing order </li>
            <li>Get the first 10 rows of the sorted dataset and save them into a new variable, <code>top_10</code>. <strong>For grading purposes, please don't modify the name of this variable</strong></li>
</div>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   

- To sort the DataFrame you can use the [`🔗sort_values()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) method. Make sure to set the arguments `by` to the column you are sorting by,  and `ascending=False` (you want descending sorting in this case). 
- To get the first ten rows of the sorted dataset, you can use the `head()` method, passing the argument 10 to overwrite the default of 5 rows.
</details>


In [6]:
# GRADED cell: Exercise 4

### START CODE HERE ###

# Sort the dataset by decreasing amount
# Note: You can pass 'by=' explicitly or just the column name string
sorted_df = sales_df.sort_values("amount", ascending=False)

# Save the top 10 sales
top_10 = sorted_df.head(10)

### END CODE HERE ###

In [7]:
# Display the results
top_10

invoice_id        date day_of_week                      product_name  \
438      534418  2010-12-02    Thursday       VINTAGE RED KITCHEN CABINET   
418      534409  2010-11-30     Tuesday   3 TIER CAKE TIN GREEN AND CREAM   
301      534399  2010-11-25    Thursday        CAKE TIN, 3 TIER RED/IVORY   
303      534399  2010-11-25    Thursday       CAKE TIN, 3 TIER MINT/IVORY   
17       534378  2010-11-22      Monday  SET/4 WHITE RETRO STORAGE CUBES    
414      534409  2010-11-30     Tuesday          REGENCY CAKESTAND 3 TIER   
360      534406  2010-11-29      Monday     CREAM SWEETHEART WALL CABINET   
53       534382  2010-11-23     Tuesday      WOODEN ADVENT CALENDAR CREAM   
508      534424  2010-11-23     Tuesday     3 TIER CAKE TIN RED AND CREAM   
564      534443  2010-12-03      Friday     3 TIER CAKE TIN RED AND CREAM   

     units_sold  price_per_unit  amount  
438           1          295.00  295.00  
418           4           14.95   59.80  
301           3           14.95   44.85  
303           3           14.95   44.85  
17            1           39.95   39.95  
414           3           12.75   38.25  
360           2           18.95   37.90  
53            2           16.95   33.90  
508           2           14.95   29.90  
564           1           29.79   29.79

<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>

<img src="img/output_ex4.png">


</details>

<a id="product-counts"></a>

### Product counts

You want to see which products are frequently bought by the customers. One way to do that is to count the number of times a product name appears in an invoice.

<a id="ex5"></a>

#### Exercise 5: Product name per row
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Use a method on the <code>product_name</code> feature of the <code>sales_df</code> DataFrame to count how often each one occurs.</li>
            <li>Store the result in the <code>product_counts</code> variable.</li>
</div>


<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
- use the `value_counts()` method on the 'product_name' column.


In [8]:
# GRADED cell: Exercise 5

### START CODE HERE ###

# Find out which product name appears most frequently.
product_counts = sales_df['product_name'].value_counts()

### END CODE HERE ###

In [9]:
# Preview the results
product_counts.head()

product_name
HAND WARMER BIRD DESIGN           8
HAND WARMER OWL DESIGN            8
HAND WARMER RED RETROSPOT         7
CHRISTMAS CRAFT LITTLE FRIENDS    7
HAND WARMER SCOTTY DOG DESIGN     6
Name: count, dtype: int64

<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>

```text
HAND WARMER BIRD DESIGN           8
HAND WARMER OWL DESIGN            8
HAND WARMER RED RETROSPOT         7
CHRISTMAS CRAFT LITTLE FRIENDS    7
HAND WARMER SCOTTY DOG DESIGN     6
Name: count, dtype: int64
```


</details>

This tells you that "HAND WARMER BIRD DESIGN" appeared on eight invoices. However, it doesn't take into account how many units are sold. For example, there could be 3 units sold in one invoice. You want to consider this as well in your tally.

<a id="ex6"></a>

#### Exercise 6: Units sold per product name
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Group the <code>sales_df</code> DataFrame by <code>product_name</code>. Store the results in <code>grouped_by_product_name</code>.</li>
            <li>Calculate the sum of <code>units_sold</code> in the <code>grouped_by_product_name</code> object. Store the results in <code>unit_counts</code>.</li>
        </ol>
</div>


<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   

- Use the `groupby()` method for grouping.
- Use the `sum()` method for calculating the sum.
</details>

In [10]:
# GRADED cell: Exercise 6

### START CODE HERE ###

grouped_by_product_name = sales_df.groupby("product_name")

unit_counts = grouped_by_product_name["units_sold"].sum()

### END CODE HERE ###

In [11]:
# Sort and preview the results
unit_counts.sort_values(ascending=False).head()

product_name
HAND WARMER BIRD DESIGN      14
SMALL POPCORN HOLDER         13
HAND WARMER RED RETROSPOT    13
SCANDINAVIAN REDS RIBBONS    12
HAND WARMER OWL DESIGN       12
Name: units_sold, dtype: int64

<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>
<small>

```text
product_name
HAND WARMER BIRD DESIGN      14
SMALL POPCORN HOLDER         13
HAND WARMER RED RETROSPOT    13
SCANDINAVIAN REDS RIBBONS    12
HAND WARMER OWL DESIGN       12
Name: units_sold, dtype: int64
```

</small>


</details>

<a id="filtering-the-dataframe"></a>

### Filtering the DataFrame
Identify invoices with purchases of more than one `"HAND WARMER BIRD DESIGN"` to analyze the commonly bundled products.

<a id="ex7"></a>

#### Exercise 7: Filter by product name and units sold
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Filter the <code>sales_df</code> DataFrame by these two conditions:</li>
            <ul>
                <li><code>"product_name"</code> is <code>"HAND WARMER BIRD DESIGN"</code></li>
                <li><code>"units_sold"</code> is greater than <code>1</code></li>
            </ul>
            <li>Store the results in <code>df_filtered</code></li>
        </ol>
</div>


<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
- Remember when to use `[]`, `()` and `&` when filtering the DataFrame.
- You can try filtering with one condition first. If it works correctly, then add the next. Remember to use `()` to group the conditions.
</details>

In [12]:
# GRADED cell: Exercise 7

### START CODE HERE ###

# Get rows that sold more than 1 HAND WARMER BIRD DESIGN
# Remember to wrap each condition in parentheses () and use & for AND
df_filtered = sales_df[(sales_df["product_name"] == "HAND WARMER BIRD DESIGN") & (sales_df["units_sold"] > 1)]

### END CODE HERE ###

In [13]:
# Preview the results
df_filtered.head()

invoice_id        date day_of_week             product_name  units_sold  \
527      534429  2010-11-24   Wednesday  HAND WARMER BIRD DESIGN           3   
534      534431  2010-11-24   Wednesday  HAND WARMER BIRD DESIGN           3   
536      534432  2010-11-25    Thursday  HAND WARMER BIRD DESIGN           2   
550      534438  2010-11-30     Tuesday  HAND WARMER BIRD DESIGN           2   

     price_per_unit  amount  
527             2.1     6.3  
534             2.1     6.3  
536             2.1     4.2  
550             2.1     4.2

<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>
<img src='img/output_ex7.png'


</details>

Now that you have these, you can filter by invoice id to see the other items a customer purchased. You can use this to recommend items to future buyers of the popular item.

In [14]:
# Specify one invoice from the results above
index = 534438

# Filter by the invoice id
row = sales_df[(sales_df["invoice_id"]==index)]

# Print the products found in the invoice
row['product_name']

549            HAND WARMER OWL DESIGN
550           HAND WARMER BIRD DESIGN
551         HAND WARMER RED RETROSPOT
552     3 TIER CAKE TIN RED AND CREAM
553    CHRISTMAS CRAFT LITTLE FRIENDS
Name: product_name, dtype: object

<a id="total-amount-per-invoice"></a>
### Total amount per invoice
One question remains unanswered: how much are customers spending per purchase? Since each purchase (identified by `invoice_id`) can include multiple products, with each row representing one product, you don’t yet know the total amount for each sale. By grouping the rows by `invoice_id`, you can calculate the total for each purchase. The owners would also like to know how many units of their products are being sold and if it translates to higher revenue. They have many low-priced items in their catalog and they'd like to see if there is enough demand for those, or if it's better to focus on their higher-priced items.

<a id="ex8"></a>

#### (Optional) Exercise 8: Find the total amount per invoice
<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Create a pivot table with the following arguments:</li>
            <ol>
                <li>Use "invoice_id" as the index</li>
                <li>Do not use the columns argument. Go straight to values.</li>
                <li>Use the features "units_sold" and "amount" as values. Pass it as a list.</li>
                <li>Aggregate values using the sum function</li> 
            </ol>
        </ol>
</div>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
- You can use the [`🔗pivot_table()`](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html) method for DataFrames to complete this task. Since each invoice has more than one row in the original DataFrame (one for each product in the purchase), you want to create a new DataFrame with aggregated data for each individual sale. This allows you to see the total amount spent per invoice, which isn't directly available in the original data due to its row-by-product structure.
- Remember to set the arguments `index`, `values` and `aggfunc` appropriately. No need for the `columns` argument. You should pass a list to the `values` argument, since you want to use both `units_sold` and `amount` columns.
</details>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you opt not to do the exercise, you can copy paste from the solution here.
</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
```python
# create a pivot table using "invoice_id" as index.
# use the columns "units_sold" and "amount" as values, aggregating by sum
pivot_by_invoice = sales_df.pivot_table(index="invoice_id",
                                        values=["units_sold", "amount"], 
                                        aggfunc="sum")
```
</details>

In [15]:
# OPTIONAL cell: Exercise 8

### START CODE HERE ###

# create a pivot table using "invoice_id" as index.
# use the columns "units_sold" and "amount" as values, aggregating by sum
pivot_by_invoice = sales_df.pivot_table(index="invoice_id", values=["units_sold", "amount"], aggfunc="sum")

### END CODE HERE ###

In [16]:
# Inspect the total_amount Series
pivot_by_invoice.head()

amount  units_sold
invoice_id                    
534377       94.99          19
534378       39.95           1
534379       23.80           4
534380      113.35          13
534381      140.35          55

<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>

<img src="img/output_ex8.png">


</details>

<a id="descriptive-statistics"></a>

### Descriptive statistics

The owners told you that the first 20 invoices have already been accounted for. They want you to get statistics for the next 40 invoices. If you look at the datatype generated by the `pivot_table()` method above, you'll see that it is also a DataFrame.

_Note: If you skipped Exercise 8, please uncomment the code below and run it to have the correct DataFrame to work with._

In [17]:
# NOTE: Uncomment this line if you did not do exercise 8 above
# pivot_by_invoice = sales_df.pivot_table(index="invoice_id", values=["units_sold", "amount"], aggfunc="sum")

In [18]:
# Get the datatype of the pivot table output
type(pivot_by_invoice)

pandas.core.frame.DataFrame

Thus, all the attributes and methods you know about DataFrames can be applied to it. For instance, you can get a summary of the features.

In [19]:
# Get a summary of the features
pivot_by_invoice.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69 entries, 534377 to 534445
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   amount      69 non-null     float64
 1   units_sold  69 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 1.6 KB


<a id="ex9"></a>

#### Exercise 9: Slicing the DataFrame

As mentioned earlier, the owners wanted you to get a set of 40 invoices starting from the 21th invoice.

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Slice the <code>pivot_by_invoice</code> DataFrame from the 21th invoice to the 60th.</li>
        </ol>
</div>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
- Use the `iloc` property to slice the dataframe.
- Remember that Python is 0-indexed. This means the 1st invoice starts at index `0`.
- Remember that indexing ranges using `iloc` excludes the ending number. For example, if you specified `[a:b]`, it will return results from index `a` to `b-1`.
</details>

In [20]:
# GRADED cell: Exercise 9

#### START CODE HERE ###

# Get 40 rows starting on the 21th invoice.
# Python is 0-indexed, so the 21st invoice is at index 20. 
# To get 40 rows from there (20 + 40 = 60), we slice [20:60]
pbi_sliced = pivot_by_invoice.iloc[20:60]

#### END CODE HERE ###

In [21]:
# Print number of rows
print("number of rows:", len(pbi_sliced))
print()

# Print start and end rows
print(pbi_sliced.iloc[0])
print()
print(pbi_sliced.iloc[39])

number of rows: 40

amount        115.25
units_sold     65.00
Name: 534397, dtype: float64

amount        11.8
units_sold     4.0
Name: 534436, dtype: float64


<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>
<small>

```text
number of rows: 40

amount        115.25
units_sold     65.00
Name: 534397, dtype: float64

amount        11.8
units_sold     4.0
Name: 534436, dtype: float64
```

</small>


</details>

<a id="ex7"></a>
#### Exercise 10: Analyzing the amount per invoice

Now that you have that amount per invoice, let's find some statistics of the sales!

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
    <strong>▶▶▶ Directions</strong> 
        <ol>
            <li>Find the sum of all sales in the <code>pbi_sliced</code> DataFrame, and save it in the variable <code>amount_sum</code></li>
            <li>Find the mean amount per invoice in the <code>pbi_sliced</code> DataFrame, and save it in the variable <code>amount_mean</code></li>
            <li>Find the max amount in the <code>pbi_sliced</code> DataFrame, and save it in the variable <code>amount_max</code></li>
            <li>Find the correlation between the number of units and the amount per invoice and save it in the variable <code>corr_units_amount</code>. </li>
            <ul>
                <li><b>Reflect:</b> What sign do you expect this correlation to have? </li> 
                <li><b>Reflect:</b> What intensity do you expect this correlation to have (weak, moderate or strong)?</li>
            </ul>
        </ol>
</div>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;"">
If you are stuck, click here for extra hints!</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">

You can solve all of this questions using methods define for Series.
- First, you will need to select the correct column of the `pivot_by_invoice` DataFrame, in this case `amount`.
- Method [`🔗sum`](https://pandas.pydata.org/docs/reference/api/pandas.Series.sum.html) will return the sample sum of the Series, while [`🔗mean`](https://pandas.pydata.org/docs/reference/api/pandas.Series.mean.html) gives you the average.
- For getting the max value you can use the [`🔗max()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.max.html#pandas.Series.max) method
- Finally, for the correlation you can use the [`🔗corr`](https://pandas.pydata.org/docs/reference/api/pandas.Series.corr.html) method to generate the table for the two numerical variables in the dataframe.
</details>


In [22]:
# GRADED cell: Exercise 10

### START CODE HERE ###

# find the sum, mean, max in pbi_sliced
amount_sum = pbi_sliced["amount"].sum()
amount_mean = pbi_sliced["amount"].mean()
amount_max = pbi_sliced["amount"].max()

# find the correlation of the numerical variables of pbi_sliced
corr_units_amount = pbi_sliced.corr()

### END CODE HERE ###

In [23]:
# Print the results
print("The sum of all sales is:", round(amount_sum, 2))
print("The mean amount per purchase is:", round(amount_mean, 2))
print("The highest purchase amount is:", round(amount_max, 2))
print("The correlation between the amount and number of units sold per invoice is", 
      round(corr_units_amount.loc['amount']['units_sold'],4))

The sum of all sales is: 2102.03
The mean amount per purchase is: 52.55
The highest purchase amount is: 295.0
The correlation between the amount and number of units sold per invoice is 0.6193


<details>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 
<br>

```text
The sum of all sales is: 2102.03
The mean amount per purchase is: 52.55
The highest purchase amount is: 295.0
The correlation between the amount and number of units sold per invoice is 0.6193
```

</details>

**Congratulations on finishing this graded lab! If everything is running correctly, save your work and submit your code for grading.**